# Launch shell without auto-opening a TUI file manager like Yazi.
kitty_override shell=/usr/bin/fish

# Launch with custom session.
kitty_override startup_session=$HOME/.dotfiles/kitty/sessions/quick-terminal.kitty-session
